spring.application.name=ResumeAnalyxer
spring.datasource.url=jdbc:postgresql://ep-sparkling-band-aziyk2jb-pooler.c-3.ap-southeast-1.aws.neon.tech:5432/neondb?sslmode=require

spring.datasource.username=neondb_owner

spring.datasource.password=npg_Zn8i4KbleIhz

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true



spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.options.model=gemini-3-flash-preview
