#spring.application.name=ResumeAnalyxer
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url = jdbc:mysql://localhost:3306/ResumeAnalyxer
#spring.datasource.username = root
#spring.datasource.password = root1234
#spring.jpa.show-sql = true
#spring.jpa.hibernate.ddl-auto = update
spring.datasource.url=jdbc:postgresql://dpg-d9jq2d7lk1mc738m3490-a.singapore-postgres.render.com:5432/resume_analyzer_904s

spring.datasource.username=resume_analyzer_904s_user
spring.datasource.password=Jb3x0Q8hyivabWJUhJAavcgHcXZ75DkO
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.options.model=gemini-3-flash-preview
